CI/CD: add final summary job for branch protection rules
- The new job is added to the required status checks, so all iOS
  integration tests in the matrix have to pass before merge

diff --git a/.github/workflows/status-checks.yml b/.github/workflows/status-checks.yml
--- a/.github/workflows/status-checks.yml
+++ b/.github/workflows/status-checks.yml
@@ -241,6 +241,21 @@ jobs:
             --timeout 7m \
             --device=model=iphone8,orientation=portrait \
             --device=model=iphone8,orientation=landscape
+  # this summary is needed to report a final result for the ios test matrix
+  # this job is added to the branch protection rules, so the matrix has to fully pass before merge
+  integration-test-ios-summary:
+    runs-on: ubuntu-latest
+    needs: integration-test-ios  # Wait for all matrix jobs
+    if: ${{ always() }}          # Run even if a matrix job fails
+    steps:
+      - name: Check integration test results
+        run: |
+          if [ "${{ needs.integration-test-ios.result }}" == "failure" ]; then
+            echo "One or more integration tests failed."
+            exit 1
+          else
+            echo "All integration tests passed."
+          fi
   integration-test-android:
     runs-on: ubuntu-latest
     container: google/cloud-sdk:latest
